apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: ns3
  labels:
    app: my-label-1
spec:
  containers:
    - name: container1
      image: sadedil/simpleinfoserver:1.0.0
      ports:
        - containerPort: 80